Traceback (most recent call last):
  File "/Users/adithyasahasranamam/Library/Python/3.8/lib/python/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/adithyasahasranamam/Library/Python/3.8/lib/python/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/adithyasahasranamam/Library/Python/3.8/lib/python/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/adithyasahasranamam/Library/Python/3.8/lib/python/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/adithyasahasranamam/Library/Python/3.8/lib/python/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/adithyasahasranamam/Library/Python/3.8/lib/python/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/adithyasahasranamam/Library/Python/3.8/lib/python/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sklearn.linear_model import LinearRegression
model = LinearRegression().fit(data_plot.total2.to_numpy().reshape((-1, 1)), data_plot.ctrl_total2)
r_sq= model.score(data_plot.total2.to_numpy().reshape((-1, 1)), data_plot.ctrl_total2)
print('coefficient of determination:', r_sq)
print('intercept:', model.intercept_)
print('slope:', model.coef_)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-37-842a911f4396>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mfrom[0m [0msklearn[0m[0;34m.[0m[0mlinear_model[0m [0;32mimport[0m [0mLinearRegression[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mmodel[0m [0;34m=[0m [0mLinearRegression[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mfit[0m[0;34m([0m[0mdata_plot[0m[0;34m.[0m[0mtotal2[0m[0;34m.[0m[0mto_numpy[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mreshape[0m[0;34m([0m[0;34m([0m[0;34m-[0m[0;36m1[0m[0;34m,[0m [0;36m1[0m[0;34m)[0m[0;34m)[0m[0;34m,[0m [0mdata_plot[0m[0;34m.[0m[0mctrl_total2[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0mr_sq[0m[0;34m=[0m [0mmodel[0m[0;34m.[0m[0mscore[0m[0;34m([0m[0mdata_plot[0m[0;34m.[0m[0mtotal2[0m[0;34m.[0m[0mto_numpy[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mreshape[0m[0;34m([0m[0;34m([0m[0;34m-[0m[0;36m1[0m[0;34m,[0m [0;36m1[0m[0;34m)[0m[0;34m)[0m[0;34m,[0m [0mdata_plot[0m[0;34m.[0m[0mctrl_total2[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mprint[0m[0;34m([0m[0;34m'coefficient of determination:'[0m[0;34m,[0m [0mr_sq[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mprint[0m[0;34m([0m[0;34m'intercept:'[0m[0;34m,[0m [0mmodel[0m[0;34m.[0m[0mintercept_[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'sklearn'
ModuleNotFoundError: No module named 'sklearn'

